### ISSUE TITLE
Why would I want my Python app to show: 'Hello, \u2068Jane\u2069!'

### ISSUE THREAD

**Issue by HeRo002** [projectfluent/python-fluent#159]
Hi!

I don't quite understand the documentation here: 
https://www.projectfluent.org/python-fluent/fluent.runtime/stable/internals.html 

This example:
>>> greet = bundle.get_message('greet-by-name')
>>> translated, errs = bundle.format_pattern(greet.value, {'name': 'Jane'})
>>> translated
'Hello, \u2068Jane\u2069!'

Is explained like this:
You will notice the extra characters \u2068 and \u2069 in the output. These are Unicode bidi isolation characters that help to ensure that the interpolated strings are handled correctly in the situation where the text direction of the substitution might not match the text direction of the localized text. 

But why would I want my user to look at this: 'Hello, \u2068Jane\u2069!'

**Comment by zbraniecki** [comment]
> But why would I want my user to look at this: 'Hello, \u2068Jane\u2069!'

User should not see those characters. Instead, the layout engine of the UI should use those characters (invisible ones) to aid bidirectional text rendering. This is important because in case of localization it is both possible that `Hello` will be Right-To-Left, while `Jane` is Left-To-Right, and the reverse - the message may be Left-To-Right, but the name can be Right-To-Left.
Unicode Directionality Isolation Marks serve exactly that purpose.

Does it answer your question?

**Comment by HeRo002** [comment]
Yes! Thank you!
