### ISSUE TITLE
Docs and/or status of project

### ISSUE THREAD

**Issue by spookylukey** [projectfluent/python-fluent#58]
At first I was going to ask for docs on how to actually use this package. On further inspection it doesn't look like it has yet reached minimum functionality. If would be great if the README could be updated to indicate the project status.

Thanks!

**Comment by flodolo** [comment]
While waiting for someone else to reply, the project is very much alive
https://github.com/projectfluent/python-fluent/releases

> On further inspection it doesn't look like it has yet reached minimum functionality

It's used to run automation in Firefox desktop, so parsing functionalities are there, and in [Pontoon](https://pontoon.mozilla.org/) for parsing and serializing. Is there anything in particular that makes you think it didn't reach minimum functionality?

I can't really answer about 2) and 3), but they seem outside of the scope of this project (and might also explain your impression).

**Comment by spookylukey** [comment]
@flodolo thanks for the reply!

>  Is there anything in particular that makes you think it didn't reach minimum functionality?

The first thing is the lack of docs - undocumented features don't exist, in my book. As a user, you have no idea what it is supposed to do, what is stable and what is going to change etc. For Python in particular this is vital - you have no compiler that will tell you the signature of a function changed. The only contract you have is docs.

Second, the fluent project home page lists JS, Python, and Rust implementations. However, the JS implementation contains an actual interpreter and a 'format' method - https://github.com/projectfluent/fluent.js/blob/master/fluent/src/context.js#L163 and so does the Rust implementation - https://github.com/projectfluent/fluent-rs/blob/master/src/context.rs#L90 . The Python implementation does not seem to have anything like that, and that's what I thought would be minimum functionality - because without it, you cannot actually generate translations, which is the **entire point** (from the perspective of anyone reaching the project via the fluent home page, like me).

Thanks for letting me know about it's use by Pontoon etc. This confirms what I had thought - I would consider this project to currently be an internal library used by Mozilla, which happens to have its own github page, but it's really just an internal library. The features it has are determined by Mozilla's current needs only.

**None of this is meant as a criticism** or some kind of demand to do more, in terms of code or docs. It's just that given the way it is advertised, it would be helpful to be clear about these things, especially that this is not really an implementation in the sense that is used for the JS/Rust projects, because you can't actually use it to generate translations. And even the parser - without docs, including some information about API stability plus a usable change log - is not the kind of thing you can build on.

Two lines in the README would suffice to fix this e.g.:

> This project contains only a parser for ftl files, which is being used by some Mozilla projects. It does not contain code to actually generate translations.

Plus, something saying whether such code is being worked on, or would be accepted as a patch, and what it should look like etc. For someone outside Mozilla like me, there is currently nothing about this project which suggests it is really "open for business" as an open source project.

**Comment by stasm** [comment]
@spookylukey Thanks for the patience and the bump. I somehow missed the notification about this issue. My bad!

> It looks like part (1) is mainly implemented, if I started on (2) or (3) would that fit in this project? Is someone else working on that already?

We only have (1) in `python-fluent` right now because the build automation at Mozilla is mostly written in Python. On buildtime, we parse translation files to validate them, compute statistics and to create files optimized for the build process.

So far, we haven't had a strong use-case for implementing (2) nor (3). It would be fantastic if you wanted to start on them! I'm not aware of any such work going on right now.

Adding to that is the fact that with three parallel implementations, we chose JS as the reference one for now as it's the most complete one and has the best test coverage. Consequently, a lot of planning and design work happens in the fluent.js repo. When features land there we usually just port them over here to Python. Unfortunately, the docs in the fluent.js repo also leave a lot to be desired. The [2018 Roadmap](https://github.com/projectfluent/fluent/wiki/Roadmap) mentions a number of improvements wrt. developer productivity in Q3 which I can't wait to start working on. The top priority in Q2 is getting Fluent Syntax 1.0 ready for its official release this summer so that it's stable before the next Firefox ESR.

All of Fluent is currently driven by Mozilla's use-cases. We try our best to work in the open; I'm sure we can do better. Thank you for taking time to describe your experience and suggest the improvements! We want Fluent to be an open-source project and we'd love to see more contributions to it.

I'll make the changes you suggested to the project homepage and this repo's README. Starting in July, I'll put the goal of improving the documentation and the developer experience high up on the Q3 roadmap.

Thanks again!

**Comment by stasm** [comment]
> So, if there's momentum for a runtime, we might want to do in python what we do in js, and separate out the runtime parser from the tooling parser.

I really hope we don't do this. It's painful enough to have to maintain two parsers in the JS land. If anything, I'd like to continue looking for a different solution to the Fluent archeology problem.

**Comment by spookylukey** [comment]
Thanks so much for the replies @stasm! I'm likely to go silent for a bit, but I'm hoping to have a bit of time in the summer to start on this.

**Comment by spookylukey** [comment]
We know have docs on https://fluent-runtime.readthedocs.io/en/latest/ and a working `FluentBundle` implementation, this issue is resolved I think!
