### ISSUE TITLE
Release plan for fluent.runtime

### ISSUE THREAD

**Issue by spookylukey** [projectfluent/python-fluent#82]
For want of a better place to put this, I'm making an issue for this.

What is the plan for releasing?

I suggest:

1. Release `fluent.runtime` 0.1 to PyPI. It's got a working implementation, which is enough for now I think.
2. Move README docs to Sphinx/readthedocs, at least for `fluent.runtime`. This shouldn't be too much work, I'm happy to do it for `fluent.runtime`.
3. Release `fluent.syntax` to PyPI. I suggest keeping the same version number, or a minor bump, just changing the package name.
4. Get `fluent.runtime` to work with latest version of `fluent.syntax` (i.e. Fluent 0.8 spec). I already have a branch for this.
5. Do another release of `fluent.runtime` at this point.
6. Look at the second, compiler implementation of FluentBundle, and other branches I'm working on (the escapers mechanism, for example) - this is a bit down the road, so we should decide at this point when we want to do releases for these additional features.

I'm assuming that @stasm or @Pike will be responsible for all releases of fluent.syntax, and I'm happy to be responsible for releasing fluent.runtime, or for you guys to do that.

**Comment by stasm** [comment]
Thanks for filing this, @spookylukey. The plan looks good. In fact, I may have jumped the gun when I published [`fluent.syntax` 0.10](https://github.com/projectfluent/python-fluent/releases/tag/fluent.syntax%400.10.0) last week, but I hope it's all good. It's on [PyPI](https://pypi.org/project/fluent.syntax/), too.

I might need some help with setting up Sphinx/RTD for `fluent.syntax`. I'll try to follow `fluent.runtime` in that regard. Would you mind opening a PR with the changes you intend to do there for step 2?
 
> I'm assuming that @stasm or @Pike  will be responsible for all releases of fluent.syntax, and I'm happy to  be responsible for releasing fluent.runtime, or for you guys to do  that.

I'll be happy to continue doing it for `fluent.syntax`. And I'll also be happy if you did it for `fluent.runtime` :) Would you mind editing https://github.com/projectfluent/python-fluent/wiki/Publishing-to-PyPI at some point in the future, so that either of us can step in if you're not available? I know you mentioned that the publishing process of `fluent.runtime` would be a bit more complex due to its having different dependencies for different Python versions.

Would you like to publish `fluent.runtime` 0.1 today?

**Comment by Pike** [comment]
I'd love to also have a conversation about the post 0.1 story. How about opening a thread on that on discourse? That might be a good forum to chat about questions around 0.5 and 1.0 and dogfood and django-ftl or django-fluent etc ;-)

**Comment by spookylukey** [comment]
OK, great, I've released `fluent.runtime` 0.1. I didn't build binaries/wheels, just a tarball, which keeps the release instructions simple, we can add the wheels later. I've updated the wiki.
